# Generated by Django 3.1 on 2021-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('slug', models.SlugField(max_length=200)),
                ('summary', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('recommended', models.BooleanField(default=False)),
                ('popular_fiction', models.BooleanField(default=False)),
                ('business', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(related_name='books', to='pdfapp.Genre')),
            ],
        ),
    ]
